services:
  - type: web
    name: ultraship-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://sehbanalam:sehbanalam@cluster0.dv6p0ru.mongodb.net/UltraShip?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: 2b8e7c1e-4f2a-4e3b-9c1d-7a6e5f4c3b2a
